### PR TITLE
Offset clause for the \InfluxDB\Query\Builder class

### PR DESCRIPTION
**Pull request by lifekent**

### CODE REVIEW

**Comment by gianarb** [comment]
Thanks @lifekent 

[ ] Tests

**Comment by thecodeassassin** [comment]
@lifekent are you in a position to add tests to this and update the PR?

**Comment by BentCoder** [comment]
Hi all! When could this PR be merged please?

**Comment by thecodeassassin** [comment]
@BentCoder when the tests are updated.

**Comment by lifekent** [comment]
@thecodeassassin I'm really sorry about missing this. Let me know if tests should be placed in another directory.

**Comment by Dwood15** [comment]
Test were added to this, can we get this merged? @thecodeassassin

**Comment by BentCoder** [comment]
Thank you guys. I guess a small update to [Reading data](https://github.com/influxdata/influxdb-php#reading-data) section would also be very helpful for others.

**Comment by thecodeassassin** [comment]
LGTM

**Comment by thecodeassassin** [comment]
@BentCoder @lifekent Creating new release 1.14.6 that has your change

**Pull request merged**
