### PR TITLE
Add new http(s) driver using the Requests library.

### PR DESCRIPTION
**Pull request by pprkut**
This is an alternative http(s) driver that uses Requests
(https://github.com/rmccue/Requests) instead of Guzzle.

I don't really know composer all that well to know how optional libs would fit in there. Hints welcome :)

We've been using this driver in multiple projects in production settings for close to a year now, no issues at all.
However, we're also mostly using it in a write workflow.

### CODE REVIEW

**Comment by thecodeassassin** [comment]
@pprkut could you perhaps add some benchmarks ?

**Comment by pprkut** [comment]
I can certainly try. What would you be interested in seeing in those? Just request times? Memory usage?

FWIW, our interest in using Requests instead of Guzzle wasn't really performance related, but centered around Requests having less dependencies and not using PSR-7.

**Comment by SMillerDev** [comment]
@thecodeassassin just revisiting this from our TODO list. What kind of benchmarks would you want?

**Comment by pprkut** [comment]
The curl driver works good enough for us, so this is no longer needed.

**Pull request closed without merging**
