### PR TITLE
added quoting of dbname in queries

### PR DESCRIPTION
**Pull request by skazi0**
Some queries fail if DB or measurement name is a reserved keyword.
Example: CREATE DATABASE stats
Simple quoting of the names solves this problem.

### CODE REVIEW

**Comment by gianarb** [comment]
Hello @skazi0 

Thanks for your PR, can you fix the test suite? And please add a test with a reserved keyword to avoid regressions.

**Comment by skazi0** [comment]
I'm not sure what the test specific to the reserved keyword should do other than just check the generated query, which would be redundant to already existing tests.

**Comment by gianarb** [comment]
It is not redundant because it fix a particolare use case.
Add a test with a reserved keyword and please add something like

```php
/**
 * @see https://github.com/influxdata/influxdb-php/pull/36
 */
```
Thanks

**Comment by thecodeassassin** [comment]
LGTM

**Comment by gianarb** [comment]
Thanks

**Pull request merged**
