### PR TITLE
Updating Influx Database with support for writing direct payloads + Minor cleanup

### PR DESCRIPTION
**Pull request by virgofx**
- Updating Influx Database with support for writing direct payloads results in over 5x performance increase when writing large Points/Payloads.

- Corresponding Docblock updates for improved thoroughness. 

- Cleaning up some extra spaces in Point.

### CODE REVIEW

**Comment by gianarb** [comment]
Great! Can you provide some test about this new feature? 

Thanks for your effort!

**Comment by virgofx** [comment]
@gianarb Will add some tests for sure soon as I can get some free time :) Also planning on adding some more notes about system limitations on throughput using UDP driver (testing very high throughput at the moment)

**Comment by virgofx** [comment]
@gianarb There's not really capability to test the new feature as saving the payload would result in huge memory overhead in production.  I've added a sample string test using the current test suite engine; however, the tests really need to be rewritten to actually install InfluxDB locally whereby all drivers and methods can be properly tested). The current mock setup doesn't really help at all.

**Comment by gianarb** [comment]
It's good thanks.
I will merge it tomorrow I think 

thanks a lot

**Comment by virgofx** [comment]
@gianarb Thanks. We've been using it in production for past 2 days, everything is good.

**Comment by gianarb** [comment]
Thanks

**Pull request merged**
