### PR TITLE
Delay driver instantiation until it's actually needed.

### PR DESCRIPTION
**Pull request by pprkut**
This essentially removes the dependency on Guzzle if you use
an alternative driver implementation. "Essentially" since the tests
are pretty hard-wired to Guzzle, but runtime-wise it wouldn't be
needed anymore.

### CODE REVIEW

**Comment by gianarb** [comment]
This change is totally good but I am not sure that this kind of change can fit in the current stable version of the SDK. 

I am in my mind a version 2 totally agnostic about guzzle but I am not really on it right know.

@pprkut can you show me your use case? 
Thamks

**Comment by pprkut** [comment]
My use case is https://github.com/M2Mobi/influxdb-php/commit/d1679366d916dd54c1ac2753ab0c7c2f19e2e477, a driver using https://github.com/rmccue/Requests instead of Guzzle.
I was planning to file a pull request for that too, but it depends on this one and #69, so I wanted to get those in first.

Not sure how that would fit in with your planning for v2 though.

**Comment by gianarb** [comment]
#69 will be merged and released soon.. Just time to have a refactoring and make a release.

This one requires a little bit of time more sorry

**Comment by pprkut** [comment]
That's totally fine. We have our fork to use in the meantime. But the general idea would still be to get this (and the Requests driver) upstream at some point :)

**Comment by tuupola** [comment]
IMO it would be a good idea to decouple next major version influxdb-php from the actual http driver implementation. [HTTPlug](http://httplug.io/) would be perfect for this. Only bad thing is that it does not support UDP.

**Comment by thecodeassassin** [comment]
@gianarb is this still something to consider?

**Comment by pprkut** [comment]
I would still like to have this :)
FWIW, we're using this in our production environments for half a year now and it's working well for us

**Comment by thecodeassassin** [comment]
@pprkut the thing is it's not really friendly in terms of performance when you have a huge number of queries since you are creating an object every time. Can i suggest you move driver to a static property of the client class (and check if it's already instantiated). If you make this change and check the tests i can merge it.

**Comment by pprkut** [comment]
The behavior of how many objects are created didn't change. The only change is when it is instantiated. This code won't create a new driver object every time you call `query`, it will only do it the first time. Afterwards `$this->driver` is not null, and thus `getDriver` will return the already existing driver object. And if you have multiple instances of the Client class, you can just use `setDriver` to always set the same driver object.

**Comment by thecodeassassin** [comment]
My bad, you are right. LGTM

**Comment by thecodeassassin** [comment]
@pprkut thanks!

**Pull request merged**
